### PR TITLE
Upgrade to current versions of dependencies; cleanups

### PR DESCRIPTION
**Pull request by lvh**

### CODE REVIEW

**Comment by lvh** [comment]
@marcoy: I've also added code that removes the sidebars, which appeared to be necessary to get it to display properly.

Here's a screenshot of it working on manifold:

screen shot 2016-04-06 at 5 23 52 pm

You can try it out at `[org.clojars.lvh/lein-dash "0.1.2-SNAPSHOT"]` :)

**Comment by marcoy** [comment]
Wow... thank you for the contributions :)

**Comment by lvh** [comment]
Glad you liked it! Would you mind cutting a release?

**Comment by marcoy** [comment]
I will do that when I get home tonight.

**Pull request merged**
